/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ut01_tarea1_hirahii;

/**
 *
 * @author 2dama
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        tituloboton = new javax.swing.JLabel();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        encabezado.setBackground(new java.awt.Color(255, 204, 102));
        encabezado.setLayout(new java.awt.GridLayout(2, 0));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BIENVENIDO A BOLLO´S CATERING ");
        encabezado.add(titulo);

        subtitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("TU ALTERNATIVA FACÍL,CÓMODA Y SALUDABLE");
        encabezado.add(subtitulo);

        getContentPane().add(encabezado, java.awt.BorderLayout.PAGE_START);

        contenido.setBackground(new java.awt.Color(255, 204, 102));
        contenido.setForeground(new java.awt.Color(255, 255, 255));
        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloboton.setBackground(new java.awt.Color(255, 255, 255));
        tituloboton.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        tituloboton.setForeground(new java.awt.Color(255, 255, 255));
        tituloboton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloboton.setText("PULSA PARA ENTRAR A LA PÁGINA PRINCIPAL");
        contenido.add(tituloboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 580, 50));

        boton.setBackground(new java.awt.Color(255, 204, 102));
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoInicial.jpg"))); // NOI18N
        boton.setBorder(null);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        contenido.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 260));

        getContentPane().add(contenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        PantallaPrincipal principal = new PantallaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel encabezado;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloboton;
    // End of variables declaration//GEN-END:variables
}
