/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ut01_tarea1_hirahii;

import javax.swing.table.DefaultTableModel;
import ut01_tarea1_hirahii.PantallaPrincipal;
import static ut01_tarea1_hirahii.PantallaPrincipal.TablaAlta;

/**
 *
 * @author 2dama
 */
public class PantallaAlta extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAlta
     */
private PantallaPrincipal PantallaPrincipal;
    public PantallaAlta() {
        
        DefaultTableModel model = (DefaultTableModel)TablaAlta.getModel();
    }
 public PantallaAlta(PantallaPrincipal pantallaprin) {
        this.PantallaPrincipal=pantallaprin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        PNombre = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        NombreCentro = new javax.swing.JTextField();
        PComensales = new javax.swing.JPanel();
        Comensales = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NComensales = new javax.swing.JSpinner();
        Pservicios = new javax.swing.JPanel();
        Servicios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaServicios = new javax.swing.JList<>();
        Palergias = new javax.swing.JPanel();
        Alergias = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CBalergias = new javax.swing.JCheckBox();
        Pobservaciones = new javax.swing.JPanel();
        Observaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ObsArea = new javax.swing.JTextArea();
        boton = new javax.swing.JPanel();
        bAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 558));

        Encabezado.setBackground(new java.awt.Color(255, 204, 153));
        Encabezado.setLayout(new java.awt.BorderLayout());

        Titulo.setBackground(new java.awt.Color(255, 204, 153));
        Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("RELLENA EL FORMULARIO PARA DARSE DE ALTA ");
        Encabezado.add(Titulo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(Encabezado, java.awt.BorderLayout.PAGE_START);

        Contenido.setPreferredSize(new java.awt.Dimension(538, 600));
        Contenido.setLayout(new java.awt.GridLayout(6, 0));

        PNombre.setBackground(new java.awt.Color(255, 153, 0));
        PNombre.setMinimumSize(new java.awt.Dimension(100, 25));
        PNombre.setLayout(new java.awt.GridLayout(1, 0));

        Nombre.setBackground(new java.awt.Color(255, 153, 0));
        Nombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre del centro:");
        Nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nombre.setMaximumSize(new java.awt.Dimension(60, 16));
        PNombre.add(Nombre);

        NombreCentro.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        NombreCentro.setText("Centro,Residencia,Comedor social....");
        NombreCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCentroActionPerformed(evt);
            }
        });
        PNombre.add(NombreCentro);

        Contenido.add(PNombre);

        PComensales.setBackground(new java.awt.Color(255, 204, 102));
        PComensales.setForeground(new java.awt.Color(255, 204, 204));
        PComensales.setLayout(new java.awt.GridLayout(1, 0));

        Comensales.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        Comensales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comensales.setText("Numero de Comensales :");
        PComensales.add(Comensales);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        NComensales.setPreferredSize(new java.awt.Dimension(40, 22));
        jPanel1.add(NComensales);

        PComensales.add(jPanel1);

        Contenido.add(PComensales);

        Pservicios.setBackground(new java.awt.Color(255, 153, 51));
        Pservicios.setLayout(new java.awt.GridLayout(1, 0));

        Servicios.setBackground(new java.awt.Color(255, 204, 0));
        Servicios.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        Servicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Servicios.setText("¿Que servicio desea contratar?");
        Pservicios.add(Servicios);

        ListaServicios.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        ListaServicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Desayuno", "Almuerzo", "Merienda", "Cena" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaServicios);

        Pservicios.add(jScrollPane1);

        Contenido.add(Pservicios);

        Palergias.setBackground(new java.awt.Color(255, 204, 102));
        Palergias.setLayout(new java.awt.GridLayout(1, 0));

        Alergias.setBackground(new java.awt.Color(255, 204, 102));
        Alergias.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        Alergias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alergias.setText("¿Hay alérgicos?");
        Palergias.add(Alergias);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        CBalergias.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        CBalergias.setText("Alérgicos");
        CBalergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBalergiasActionPerformed(evt);
            }
        });
        jPanel6.add(CBalergias);

        Palergias.add(jPanel6);

        Contenido.add(Palergias);

        Pobservaciones.setBackground(new java.awt.Color(255, 153, 0));
        Pobservaciones.setLayout(new java.awt.GridLayout(1, 0));

        Observaciones.setBackground(new java.awt.Color(255, 153, 0));
        Observaciones.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        Observaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Observaciones.setText("Observaciones:");
        Pobservaciones.add(Observaciones);

        ObsArea.setColumns(20);
        ObsArea.setRows(5);
        jScrollPane2.setViewportView(ObsArea);

        Pobservaciones.add(jScrollPane2);

        Contenido.add(Pobservaciones);

        boton.setBackground(new java.awt.Color(255, 204, 153));
        boton.setForeground(new java.awt.Color(255, 204, 153));
        boton.setLayout(new java.awt.GridLayout(1, 0));

        bAlta.setBackground(new java.awt.Color(255, 204, 153));
        bAlta.setText("DARSE DE ALTA");
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        boton.add(bAlta);

        Contenido.add(boton);

        getContentPane().add(Contenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCentroActionPerformed

    private void CBalergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBalergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBalergiasActionPerformed

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        Cliente cliente = new Cliente( 
        NombreCentro.getText(),
        (Integer) NComensales.getValue(),
        ListaServicios.getSelectedValue(),
        CBalergias.isSelected(),
        ObsArea.getText()
    );
        DefaultTableModel model = (DefaultTableModel) TablaAlta.getModel();
        Object[] fila = new Object[]{
            cliente.getNombreCentro(), cliente.getNComensales(), cliente.getListaServicios(), cliente.isCBalergias(),cliente.getObsArea()
        };
        model.addRow(fila);
    


    // Llama al método para agregar el cliente a la tabla de PantallaPrincipal
    this.dispose(); // Cierra la ventana de alta

    
    }//GEN-LAST:event_bAltaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alergias;
    private javax.swing.JCheckBox CBalergias;
    private javax.swing.JLabel Comensales;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JList<String> ListaServicios;
    private javax.swing.JSpinner NComensales;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreCentro;
    private javax.swing.JTextArea ObsArea;
    private javax.swing.JLabel Observaciones;
    private javax.swing.JPanel PComensales;
    private javax.swing.JPanel PNombre;
    private javax.swing.JPanel Palergias;
    private javax.swing.JPanel Pobservaciones;
    private javax.swing.JPanel Pservicios;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bAlta;
    private javax.swing.JPanel boton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}