/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ut01_tarea1_hirahii;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2dama
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        encabezado = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        ptabla = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        TablaAlta = new javax.swing.JTable();
        menu = new javax.swing.JMenuBar();
        alta = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        jPopupMenu1.setToolTipText("");
        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.setLabel("Que desea");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encabezado.setBackground(new java.awt.Color(255, 204, 102));
        encabezado.setForeground(new java.awt.Color(255, 255, 255));

        titulo.setBackground(new java.awt.Color(255, 204, 153));
        titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INFORMACIÓN SOBRE LOS CLIENTES DE ALTA");
        titulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout encabezadoLayout = new javax.swing.GroupLayout(encabezado);
        encabezado.setLayout(encabezadoLayout);
        encabezadoLayout.setHorizontalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        encabezadoLayout.setVerticalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(encabezado, java.awt.BorderLayout.PAGE_START);

        ptabla.setBackground(new java.awt.Color(255, 204, 102));

        TablaAlta.setBackground(new java.awt.Color(255, 204, 51));
        TablaAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaAlta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "NºComensales", "Comidas", "Alérgicos", "Observaciones"
            }
        ));
        TablaAlta.setGridColor(new java.awt.Color(255, 204, 153));
        scroll.setViewportView(TablaAlta);

        javax.swing.GroupLayout ptablaLayout = new javax.swing.GroupLayout(ptabla);
        ptabla.setLayout(ptablaLayout);
        ptablaLayout.setHorizontalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        ptablaLayout.setVerticalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptablaLayout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(ptabla, java.awt.BorderLayout.CENTER);

        menu.setBackground(new java.awt.Color(255, 204, 153));

        alta.setText("Alta");
        alta.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                altaMenuSelected(evt);
            }
        });
        alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaMouseClicked(evt);
            }
        });
        menu.add(alta);

        salir.setText("Salir");
        salir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                salirMenuSelected(evt);
            }
        });
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        menu.add(salir);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void altaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_altaMenuSelected
        
    }//GEN-LAST:event_altaMenuSelected

    private void salirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_salirMenuSelected
       
    }//GEN-LAST:event_salirMenuSelected

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void altaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaMouseClicked
        PantallaAlta pantallaAlta = new PantallaAlta(this);
        pantallaAlta.setVisible(true);
    }//GEN-LAST:event_altaMouseClicked
    
    public void agregarCliente() {
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaAlta;
    private javax.swing.JMenu alta;
    private javax.swing.JPanel encabezado;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel ptabla;
    private javax.swing.JMenu salir;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
